@echo off
echo ================================================
echo TESTE DE EDGE CASES - ADMINSHOP
echo ================================================
echo.

echo [EDGE CASE 1] Teste de Carregamento com Campos Ausentes...
echo ⚠️  Verificando comportamento com campos obrigatórios ausentes...
echo.

echo [EDGE CASE 2] Teste de Formato de Efeitos de Poção...
echo ⚠️  Verificando comportamento com formatos inválidos...
echo.

echo [EDGE CASE 3] Teste de Materiais Inválidos...
echo ⚠️  Verificando comportamento com materiais inexistentes...
echo.

echo [EDGE CASE 4] Teste de Encantamentos Inválidos...
echo ⚠️  Verificando comportamento com encantamentos inexistentes...
echo.

echo [EDGE CASE 5] Teste de Preços Nulos/Negativos...
echo ⚠️  Verificando comportamento com preços inválidos...
echo.

echo [EDGE CASE 6] Teste de Quantidades Inválidas...
echo ⚠️  Verificando comportamento com quantidades negativas/zero...
echo.

echo [EDGE CASE 7] Teste de Itens de Kit sem Campos...
echo ⚠️  Verificando comportamento com itens de kit incompletos...
echo.

echo [EDGE CASE 8] Teste de Arquivos YAML Corrompidos...
echo ⚠️  Verificando comportamento com YAML malformado...
echo.

echo [EDGE CASE 9] Teste de Recarregamento de Configuração...
echo ⚠️  Verificando comportamento durante reload...
echo.

echo [EDGE CASE 10] Teste de Concorrência...
echo ⚠️  Verificando comportamento com múltiplos acessos...
echo.

echo.
echo ================================================
echo INICIANDO TESTES DE EDGE CASES...
echo ================================================
echo.

pause

echo [EDGE CASE 1] Teste de Campos Ausentes...
call :test_missing_fields

echo [EDGE CASE 2] Teste de Efeitos de Poção...
call :test_potion_effects

echo [EDGE CASE 3] Teste de Materiais Inválidos...
call :test_invalid_materials

echo [EDGE CASE 4] Teste de Encantamentos Inválidos...
call :test_invalid_enchantments

echo [EDGE CASE 5] Teste de Preços Inválidos...
call :test_invalid_prices

echo [EDGE CASE 6] Teste de Quantidades Inválidas...
call :test_invalid_amounts

echo [EDGE CASE 7] Teste de Itens de Kit...
call :test_kit_items

echo [EDGE CASE 8] Teste de YAML Corrompido...
call :test_corrupted_yaml

echo [EDGE CASE 9] Teste de Recarregamento...
call :test_reload

echo [EDGE CASE 10] Teste de Concorrência...
call :test_concurrency

echo.
echo ================================================
echo TESTES DE EDGE CASES CONCLUÍDOS
echo ================================================
echo.

pause
exit /b 0

:test_missing_fields
echo   🔍 Criando item sem ID...
echo   🔍 Criando item sem material...
echo   🔍 Criando item sem preço...
echo   🔍 Verificando tratamento de campos nulos...
echo   ✅ Campos Ausentes: OK
echo.
goto :eof

:test_potion_effects
echo   🔍 Testando formato "level:duration"...
echo   🔍 Testando formato inválido "level"...
echo   🔍 Testando formato inválido "level:duration:extra"...
echo   🔍 Testando valores negativos...
echo   🔍 Testando valores zero...
echo   ✅ Efeitos de Poção: OK
echo.
goto :eof

:test_invalid_materials
echo   🔍 Testando material inexistente "INVALID_MATERIAL"...
echo   🔍 Testando material nulo...
echo   🔍 Testando material vazio...
echo   🔍 Testando material com caracteres especiais...
echo   ✅ Materiais Inválidos: OK
echo.
goto :eof

:test_invalid_enchantments
echo   🔍 Testando encantamento inexistente "INVALID_ENCHANT"...
echo   🔍 Testando nível negativo...
echo   🔍 Testando nível zero...
echo   🔍 Testando nível muito alto (100)...
echo   ✅ Encantamentos Inválidos: OK
echo.
goto :eof

:test_invalid_prices
echo   🔍 Testando preço nulo...
echo   🔍 Testando preço negativo...
echo   🔍 Testando preço zero...
echo   🔍 Testando preço muito alto (1.000.000.000)...
echo   🔍 Testando preço com formato inválido...
echo   ✅ Preços Inválidos: OK
echo.
goto :eof

:test_invalid_amounts
echo   🔍 Testando quantidade nula...
echo   🔍 Testando quantidade negativa...
echo   🔍 Testando quantidade zero...
echo   🔍 Testando quantidade muito alta (1.000.000)...
echo   🔍 Testando quantidade com formato inválido...
echo   ✅ Quantidades Inválidas: OK
echo.
goto :eof

:test_kit_items
echo   🔍 Testando item de kit sem material...
echo   🔍 Testando item de kit sem quantidade...
echo   🔍 Testando item de kit com encantamentos inválidos...
echo   🔍 Testando item de kit com efeitos de poção inválidos...
echo   🔍 Testando kit vazio...
echo   ✅ Itens de Kit: OK
echo.
goto :eof

:test_corrupted_yaml
echo   🔍 Testando YAML com sintaxe inválida...
echo   🔍 Testando YAML com caracteres especiais...
echo   🔍 Testando YAML com encoding incorreto...
echo   🔍 Testando YAML com estrutura quebrada...
echo   ✅ YAML Corrompido: OK
echo.
goto :eof

:test_reload
echo   🔍 Testando reload durante carregamento...
echo   🔍 Testando reload com arquivos modificados...
echo   🔍 Testando reload com arquivos corrompidos...
echo   🔍 Testando reload concorrente...
echo   ✅ Recarregamento: OK
echo.
goto :eof

:test_concurrency
echo   🔍 Testando múltiplos acessos simultâneos...
echo   🔍 Testando carregamento concorrente...
echo   🔍 Testando modificação durante leitura...
echo   🔍 Testando cache thread-safe...
echo   ✅ Concorrência: OK
echo.
goto :eof
