# Prime League Core - Configuração Econômica e de Doadores
# Versão: 2.0.0

economy:
  # Limites de transação (anti-inflacionário)
  max_transaction_amount: 10000.0
  min_shop_price: 0.01
  initial_balance: 100.0
  initial_elo: 1000  # ELO inicial para novos jogadores
  
  # Taxas e custos
  transaction_fee_rate: 0.01  # 1% de taxa por transação
  market_tax_rate: 0.05       # 5% de taxa no mercado
  shop_maintenance_fee: 10.0  # Taxa diária de manutenção de lojas
  
  # Configurações de doador
  donor_discount_rate: 0.10   # 10% de desconto base para doadores
  
  # Logs e auditoria
  enable_transaction_logs: true
  log_level: "INFO"  # DEBUG, INFO, WARNING

donors:
  # Sistema de níveis de doador configurável
  levels:
    0: # Nível Padrão (Apenas Acesso Prime)
      name: "Player"
      chat-tag: "&7"
      discount: 0.0
      max-alt-accounts: 1
      min_donation: 0.0
      permissions:
        - "primeleague.basic.access"
    
    1:
      name: "Apoiador"
      chat-tag: "&7[Apoiador]"
      discount: 0.05
      max-alt-accounts: 3
      min_donation: 10.0
      permissions:
        - "primeleague.donor.apoiador"
        - "primeleague.shop.discount"
        - "primeleague.chat.color"
    
    2:
      name: "Patrocinador"
      chat-tag: "&6[Patrocinador]"
      discount: 0.10
      max-alt-accounts: 5
      min_donation: 25.0
      permissions:
        - "primeleague.donor.patrocinador"
        - "primeleague.shop.discount"
        - "primeleague.chat.color"
        - "primeleague.chat.format"

# Configurações de banco de dados
database:
  host: 127.0.0.1
  port: 3306
  name: primeleague
  user: root
  password: root
  pool:
    maximumPoolSize: 10
    minimumIdle: 2
    connectionTimeoutMs: 10000
    idleTimeoutMs: 600000
    maxLifetimeMs: 1800000
  jdbcParams: useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
  connectionTestQuery: SELECT 1
  
  # Tabelas específicas da economia
  economy_table: "player_economy"
  donor_table: "donors"
  transaction_log_table: "economy_transactions"
  
  # ========================================
  # VALIDAÇÃO DE SCHEMA (O GUARDIÃO)
  # ========================================
  validation:
    fail-on-mismatch: true     # Parar servidor se houver inconsistências
    log-level: "DETAILED"       # NONE, ERRORS, DETAILED
    auto-fix: false             # Tentar corrigir automaticamente (PERIGOSO)
    health-check-interval: 3600 # Verificação de saúde a cada 1 hora
    
    # Validações específicas
    validate-table-structure: true    # Validar estrutura das tabelas
    validate-constraints: true        # Validar foreign keys e constraints
    validate-data-integrity: true     # Executar validações de dados
    validate-indexes: false           # Validar índices (opcional)
  
# Configurações de segurança
security:
  max_daily_transactions: 1000  # Limite diário de transações por jogador
  suspicious_amount_threshold: 5000.0  # Valor que dispara alerta de segurança
  enable_fraud_detection: true

# Configurações da API HTTP
api:
  port: 8080  # Porta para o servidor HTTP da API
  enabled: true  # Habilitar/desabilitar API HTTP
  security:
    enabled: true  # Habilitar autenticação
    bearer_token: "primeleague_api_token_2024"  # Token único para autenticação
    rate_limit:
      requests_per_minute: 60  # Limite de requisições por minuto
      burst_limit: 10  # Limite de burst (requisições simultâneas)
  cors:
    enabled: true
    allowed_origins: ["*"]  # Em produção, especificar domínios específicos


